#!/bin/bash
#SBATCH --job-name=run_trim --output=z01.%x
#SBATCH --mail-type=END,FAIL --mail-user=mjk336@georgetown.edu
#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --time=72:00:00
#SBATCH --mem=4G

#---------------------------------------------------------------------------------------#
# This script runs trimmomatic v0.39 on paired end fastq files (w/ no variables)     #
#---------------------------------------------------------------------------------------#

#- set environment, load module------------------------------------------------#
shopt -s expand_aliases
module load trimmomatic
#------------------------------------------------------------------------------#

#- run trimmomatic-------------------------------------------------------------#
trimmomatic PE \
/home/mjk336/WTA2_1.fq.gz \
/home/mjk336/WTA2_2.fq.gz \
/home/mjk336/WTA2_1.trPE.fq.gz WTA2_2.trPE.fq.gz \
/home/mjk336/WTA2_1.trSE.fq.gz WTA2_2.trSE.fq.gz \
ILLUMINACLIP:/home/mjk336/TruSeq3-PE.fa:2:30:10 \
HEADCROP:15 \
TRAILING:20 \
SLIDINGWINDOW:4:15 \
MINLEN:75

module unload trimmomatic



#- FIN -----------------------------------------------------------------------#
