#!/bin/bash
#SBATCH --job-name=run_trim1.SBATCH --output=z01.%x
#SBATCH --mail-type=END,FAIL --mail-user=mjk336@georgetown.edu
#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --time=72:00:00
#SBATCH --mem=4G

#---------------------------------------------------------------------------------------#
# This script runs trimmomatic v0.39 on paired end fastq files (w/ no variables)     #
#---------------------------------------------------------------------------------------#

#- set environment, load module------------------------------------------------#
shopt -s expand_aliases
module load trimmomatic
#------------------------------------------------------------------------------#

#- run trimmomatic-------------------------------------------------------------#
trimmomatic PE \
/home/mjk336/HW4_input_files/EC-12_R1_001.fastq.gz \
/home/mjk336/HW4_input_files/EC-12_R2_001.fastq.gz \
/home/mjk336/HW4_output_files/EC-12_R1_trmPE.fq.gz /home/mjk336/HW4_output_files/EC-12_R1_trmSE.fq.gz \
/home/mjk336/HW4_output_files/EC-12_R2_trmPE.fq.gz /home/mjk336/HW4_output_files/EC-12_R2_trmSE.fq.gz  \
LEADING:10 \
TRAILING:10 \
ILLUMINACLIP:/home/mjk336/HW4_input_files/TruSeq3-PE.fa:2:30:10 \
SLIDINGWINDOW:4:15 \
MINLEN:75

module unload trimmomatic



#- FIN -----------------------------------------------------------------------#
